from setuptools import setup, find_packages

setup(
    name="keyword-news-scraping",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "requests>=2.32.3",
        "beautifulsoup4>=4.13.4",
        "lxml>=5.4.0",
        "httpx>=0.28.1",
        "curl-cffi>=0.11.2",
        "pandas>=2.3.0",
        "numpy>=2.0.2",
        "matplotlib>=3.9.4",
        "yfinance>=0.2.61",
        "pykrx>=1.0.51",
        "python-telegram-bot>=22.1",
        "peewee>=3.18.1",
        "python-dotenv>=1.1.0",
        "xlrd>=2.0.1",
        "websockets>=15.0.1",
    ],
    python_requires=">=3.9",
    author="Yoonwoo Kye",
    author_email="mryoonwoo@gmail.com",
    description="A project for scraping and analyzing news articles from Google News",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/GrilledSalmon/keyword-news-scraping",
    classifiers=[
        "Programming Language :: Python :: 3.9",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
) 