name: Daily News Crawler

on:
  schedule:
    # 매일 오전 7시 30분 (한국시간) = UTC 오후 10시 30분 (전날)
    - cron: '30 22 * * *'
    # 매일 오후 10시 (한국시간) = UTC 오후 1시
    - cron: '0 13 * * *'
  workflow_dispatch: # 수동 실행도 가능

jobs:
  crawl-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
        echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
        
    - name: Create logs directory
      run: mkdir -p logs
      
    - name: Run crawler
      run: python scripts/run_crawler.py
      
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: crawler-logs
        path: logs/
        retention-days: 30 